services:
  - type: web
    name: plagix-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        value: django-insecure-REPLACE_ME_WITH_YOUR_OWN_SECRET
      - key: OPENAI_API_KEY
        value: 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
